const ApiError = require('../exceptions/api-error');

class UserController {
  /**
   * * Создать школу
   */
  async login(req, res, next) {
    try {
    } catch (e) {
      next(e);
    }
  }

  /**
   * * Выход из аккаунта
   */
  async logout(req, res, next) {
    try {
    } catch (e) {
      next(e);
    }
  }

  /**
   * * Активация аккаунта
   */
  async activate(req, res, next) {
    try {
    } catch (e) {
      next(e);
    }
  }

  /**
   * * Активация аккаунта
   */
  async activate(req, res, next) {
    try {
    } catch (e) {
      next(e);
    }
  }

  /**
   * * Обновление токенов пользователя
   */
  async refresh(req, res, next) {
    try {
    } catch (e) {
      next(e);
    }
  }
}

module.exports = new UserController();
